### PR TITLE
Only change orderby when is has not been set

### PR DESCRIPTION
**Pull request by sboerrigter**
Only change orderby when is has not been set

### CODE REVIEW

**Comment by haroldangenent** [comment]
Thanks for contributing.

Just tested this. This approach doesn't seem to work for `get_posts()`, since it automatically sets `orderby` to `post_date`. This causes `orderby` to always be set, and posts would never be ordered automatically (when using `get_posts()`).

An option would be to built a filter like `suppress_auto_order` or something, that you could specify to be false so auto-ordering would not be applied.

**Comment by sboerrigter** [comment]
U suggest we remove the auto sort function from the plugin and update the readme file (see my latest commits). We should update the version number to 2.0.0 since these changes are breaking.

I also applied the PSR coding standards.

What do you think?

**Comment by haroldangenent** [comment]
This seems cool. I have just used [Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer) to test PSR-2 compatibility, but I still get 262 validation errors. Could you fix those?

Since this update is breaking, I want to test the entire plugin again and improve it as much as possible (so we won't have to break things in the future).

**Comment by haroldangenent** [comment]
By the way, this should fix: #1 and #3. Did you take a look at #3 already?

**Comment by sboerrigter** [comment]
I've fixed the PSR validation errors. There is only one warning left in the main file because I defined the plugin path constant here. I don't know if we can (and want to) fix this.

About #3. I didn't get any strict standards notices. So I guess it's already solved with the PSR stuff?

**Comment by haroldangenent** [comment]
Just tested the PR globally, some feedback:

- It doesn't work anymore. After re-ordering some posts and refreshing, it goes back to it's previous state;
- When using the optional Step 3 from the README.md, I get a fatal error;
- When using the second part of Step 3, the function and class don't exist;
- This indentation seems weird: https://github.com/trendwerk/post-type-order/blob/orderby/assets/includes/PostTypeOrder.php#L86-135;
- According to the [SoC](https://en.wikipedia.org/wiki/Separation_of_concerns) principle, we may not want to put this all in one file. Since we're rewriting it anyway, we should probably do it right;
- The code doesn't conform to the PSR-4 standard for autoloading, so it's technically not PSR-2.

I couldn't test this thoroughly yet, because some stuff stopped working.

**Comment by haroldangenent** [comment]
Oh and since visibility is now declared on all methods, the visibility value should be considered. Every method is public at this moment, is that really the best thing to do?

**Comment by sboerrigter** [comment]
**It doesn't work anymore. After re-ordering some posts and refreshing, it goes back to it's previous state;**
I cannot reproduce this issue. Do you get a javascript error? If so, can you post them here?

**When using the optional Step 3 from the README.md, I get a fatal error;**
I see. Can you please look into this? I don't know how this plugin works exactly.

**When using the second part of Step 3, the function and class don't exist;**
I cannot test this right nog due to the fatal error.

**This indentation seems weird: https://github.com/trendwerk/post-type-order/blob/orderby/assets/includes/PostTypeOrder.php#L86-135;**
Changed it.

**According to the SoC principle, we may not want to put this all in one file. Since we're rewriting it anyway, we should probably do it right;**
Can you do this? You created this plugin.

**The code doesn't conform to the PSR-4 standard for autoloading, so it's technically not PSR-2.**
I've added an autoloader.

**Oh and since visibility is now declared on all methods, the visibility value should be considered. Every method is public at this moment, is that really the best thing to do?**
I'm not sure what visibility values I should use. Can you look at this?

**Comment by haroldangenent** [comment]
Closing this because of inactivity and because the PR code is already outdated.

**Pull request closed without merging**
